spring.application.name=featureflagms

server.port=8080

#Postgres SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/feature_flags
spring.datasource.username=postgres
spring.datasource.password=prakhar123
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect